export const WEB_REQUEST_RESOURCE_TYPES = [
  'beacon',
  'csp_report',
  'font',
  'image',
  'imageset',
  'json',
  'main_frame',
  'media',
  'object',
  'object_subrequest',
  'ping',
  'script',
  'speculative',
  'stylesheet',
  'sub_frame',
  'web_manifest',
  'websocket',
  'xml_dtd',
  'xmlhttprequest',
  'xslt',
  'other',
] as const;
export type WebRequestResourceType = typeof WEB_REQUEST_RESOURCE_TYPES[number];
